export const TYPES = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	UserController: Symbol.for('UserController'),
	ExeptionFilter: Symbol.for('ExeptionFilter'),
	UserService: Symbol.for('IUserService'),
	ConfigService: Symbol.for('IConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	UsersRepository: Symbol.for('UsersRepository'),
	LessonsRepository: Symbol.for('LessonsRepository'),
	LessonsService: Symbol.for('LessonsService'),
	LessonsController: Symbol.for('LessonsController'),
	StudentsRepository: Symbol.for('StudentsRepository'),
	StudentsService: Symbol.for('StudentsService'),
	StudentsController: Symbol.for('StudentsController'),
};
